spare_parts_loot_table = {
    {["loot_id"] = "30870",["loot_name"] = "Cuffs of Devastation",["prio"] = "Arcane Mage > Balance Druid > Elemental Shaman",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Rage Winterchill",},
    {["loot_id"] = "30863",["loot_name"] = "Deadly Cuffs",["prio"] = "DPS Warrior > Enhancement Shaman",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Rage Winterchill",},
    {["loot_id"] = "30868",["loot_name"] = "Rejuvenating Bracers",["prio"] = "Resto Druid",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Rage Winterchill",},
    {["loot_id"] = "30862",["loot_name"] = "Blessed Adamantite Bracers",["prio"] = "Holy Paladin",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Rage Winterchill",},
    {["loot_id"] = "30872",["loot_name"] = "Chronicle of Dark Secrets",["prio"] = "Arcane Mage = Destruction Warlock > Balance Druid = Elemental Shaman > Shadow Priest",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Rage Winterchill",},
    {["loot_id"] = "30888",["loot_name"] = "Anetheron's Noose",["prio"] = "Arcane Mage > Balance Druid = Destruction Warlock",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Anetheron",},
    {["loot_id"] = "30879",["loot_name"] = "Don Alejandro's Money Belt",["prio"] = "Survival Hunter > BM Hunter > Feral Druid",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Anetheron",},
    {["loot_id"] = "30881",["loot_name"] = "Blade of Infamy",["prio"] = "Survival Hunter > BM Hunter > Rogue > DPS Warrior",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Anetheron",},
    {["loot_id"] = "30883",["loot_name"] = "Pillar of Ferocity",["prio"] = "Feral Druid (Bear) > Feral Druid (Cat)",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Anetheron",},
    {["loot_id"] = "30882",["loot_name"] = "Bastion of Light",["prio"] = "Resto Shaman > Holy Paladin",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Anetheron",},
    {["loot_id"] = "30895",["loot_name"] = "Angelista's Sash",["prio"] = "Holy Priest > Resto Druid",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Kaz'Rogal",},
    {["loot_id"] = "30916",["loot_name"] = "Leggings of Channeled Elements",["prio"] = "Shadow Priest > Elemental Shaman > Balance Druid > Destruction Warlock",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Kaz'Rogal",},
    {["loot_id"] = "30914",["loot_name"] = "Belt of the Crescent Moon",["prio"] = "Balance Druid > Elemental Shaman",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Kaz'Rogal",},
    {["loot_id"] = "30893",["loot_name"] = "Sun-touched Chain Leggings",["prio"] = "Resto Shaman = Holy Paladin",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Kaz'Rogal",},
    {["loot_id"] = "30918",["loot_name"] = "Hammer of Atonement",["prio"] = "Holy Paladin > Resto Shaman > Holy Priest > Resto Druid",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Kaz'Rogal",},
    {["loot_id"] = "30889",["loot_name"] = "Kaz'rogal's Hardened Heart",["prio"] = "Prot Warrior",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Kaz'Rogal",},
    {["loot_id"] = "30900",["loot_name"] = "Bow-stitched Leggings",["prio"] = "Survival Hunter > Ret Paladin = Enhancement Shaman > BM Hunter",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Azgalor",},
    {["loot_id"] = "30897",["loot_name"] = "Girdle of Hope",["prio"] = "Holy Paladin",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Azgalor",},
    {["loot_id"] = "30901",["loot_name"] = "Boundless Agony",["prio"] = "BM Hunter",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Azgalor",},
    {["loot_id"] = "31092",["loot_name"] = "Gloves of the Forgotten Conqueror",["prio"] = "Prot Paladin > Destruction Warlock > Shadow Priest > Holy Priest",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Azgalor",},
    {["loot_id"] = "31094",["loot_name"] = "Gloves of the Forgotten Protector",["prio"] = "BM Hunter > Survival Hunter > Elemental Shaman > 2H Arms Warrior 4 Piece > Resto Shaman > Fury Warrior 4 Piece > Kebab 4 Piece",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Azgalor",},
    {["loot_id"] = "31093",["loot_name"] = "Gloves of the Forgotten Vanquisher",["prio"] = "Feral Druid (Bear) > Rogue > Feral Druid (Cat) > Balance Druid",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Azgalor",},
    {["loot_id"] = "30912",["loot_name"] = "Leggings of Eternity",["prio"] = "Holy Priest > Resto Druid",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Archimonde",},
    {["loot_id"] = "30905",["loot_name"] = "Midnight Chestguard",["prio"] = "Ret Paladin > Enhancement Shaman > Rogue > DPS Warrior",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Archimonde",},
    {["loot_id"] = "30911",["loot_name"] = "Scepter of Purification",["prio"] = "Holy Priest = Resto Druid",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Archimonde",},
    {["loot_id"] = "30910",["loot_name"] = "Tempest of Chaos",["prio"] = "Prot Paladin > Arcane Mage >= Destruction Warlock",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Archimonde",},
    {["loot_id"] = "30902",["loot_name"] = "Cataclysm's Edge",["prio"] = "2H Arms Warrior > Ret Paladin",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Archimonde",},
    {["loot_id"] = "30908",["loot_name"] = "Apostle of Argus",["prio"] = "Resto Druid > Holy Priest > Resto Shaman",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Archimonde",},
    {["loot_id"] = "30909",["loot_name"] = "Antonidas's Aegis of Rapt Concentration",["prio"] = "Elemental Shaman > Prot Paladin",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Archimonde",},
    {["loot_id"] = "30906",["loot_name"] = "Bristleblitz Striker",["prio"] = "BM Hunter > Survival Hunter",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Archimonde",},
    {["loot_id"] = "31097",["loot_name"] = "Helm of the Forgotten Conqueror",["prio"] = "Prot Paladin > Destruction Warlock > Shadow Priest > Holy Paladin > Holy Priest",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Archimonde",},
    {["loot_id"] = "31095",["loot_name"] = "Helm of the Forgotten Protector",["prio"] = "Survival Hunter > 2H Arms Warrior 4 Piece > Elemental Shaman > Resto Shaman > BM Hunter 4 piece = Fury Warrior 4 Piece > Kebab 4 Piece",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Archimonde",},
    {["loot_id"] = "31096",["loot_name"] = "Helm of the Forgotten Vanquisher",["prio"] = "Feral Druid (Bear) > Rogue > Feral Druid (Cat) > Balance Druid > Resto Druid",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Archimonde",},
    {["loot_id"] = "32590",["loot_name"] = "Nethervoid Cloak",["prio"] = "Shadow Priest > Destruction Warlock",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Trash",},
    {["loot_id"] = "34010",["loot_name"] = "Pepe's Shroud of Pacification",["prio"] = "Prot Warrior >= Prot Paladin",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Trash",},
    {["loot_id"] = "32609",["loot_name"] = "Boots of the Divine Light",["prio"] = "Holy Priest >= Resto Druid > Resto Shaman",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Trash",},
    {["loot_id"] = "32591",["loot_name"] = "Choker of Serrated Blades",["prio"] = "BM Hunter > DPS Warrior > Enhancement Shaman > Feral Druid (Cat)/Warden = Rogue",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Trash",},
    {["loot_id"] = "34009",["loot_name"] = "Hammer of Judgement",["prio"] = "Prot Paladin > Shadow Priest > Balance Druid > Elemental Shaman",["loot_zone"] = "Mount Hyjal",["loot_bosses"] = "Trash",},
    {["loot_id"] = "32239",["loot_name"] = "Slippers of the Seacaller",["prio"] = "Arcane Mage > Destruction Warlock > Shadow Priest > Elemental Shaman = Balance Druid",["loot_zone"] = "Black Temple",["loot_bosses"] = "High Warlord Naj'entus",},
    {["loot_id"] = "32234",["loot_name"] = "Fists of Mukoa",["prio"] = "Enhancement Shaman > MS>OS",["loot_zone"] = "Black Temple",["loot_bosses"] = "High Warlord Naj'entus",},
    {["loot_id"] = "32243",["loot_name"] = "Pearl Inlaid Boots",["prio"] = "Holy Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "High Warlord Naj'entus",},
    {["loot_id"] = "32245",["loot_name"] = "Tide-stomper's Greaves",["prio"] = "Prot Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "High Warlord Naj'entus",},
    {["loot_id"] = "32238",["loot_name"] = "Ring of Calming Waves",["prio"] = "Holy Paladin > MS>OS",["loot_zone"] = "Black Temple",["loot_bosses"] = "High Warlord Naj'entus",},
    {["loot_id"] = "32237",["loot_name"] = "The Maelstrom's Fury",["prio"] = "Elemental Shaman = Shadow Priest > Balance Druid",["loot_zone"] = "Black Temple",["loot_bosses"] = "High Warlord Naj'entus",},
    {["loot_id"] = "32236",["loot_name"] = "Rising Tide",["prio"] = "DPS Warrior > Enhancement Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "High Warlord Naj'entus",},
    {["loot_id"] = "32248",["loot_name"] = "Halberd of Desolation",["prio"] = "Hunter",["loot_zone"] = "Black Temple",["loot_bosses"] = "High Warlord Naj'entus",},
    {["loot_id"] = "32256",["loot_name"] = "Waistwrap of Infinity",["prio"] = "Shadow Priest > Destruction Warlock > Arcane Mage = Balance Druid > Elemental Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "Supremus",},
    {["loot_id"] = "32258",["loot_name"] = "Naturalist's Preserving Cinch",["prio"] = "Resto Shaman > Holy Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Supremus",},
    {["loot_id"] = "32260",["loot_name"] = "Choker of Endless Nightmares",["prio"] = "DPS Warrior > Enhancement Shaman = Rogue > BM Hunter = Ret Paladin = Feral Druid (Cat)/Warden",["loot_zone"] = "Black Temple",["loot_bosses"] = "Supremus",},
    {["loot_id"] = "32261",["loot_name"] = "Band of the Abyssal Lord",["prio"] = "Prot Warrior = Prot Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Supremus",},
    {["loot_id"] = "32254",["loot_name"] = "The Brutalizer",["prio"] = "Prot Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Supremus",},
    {["loot_id"] = "32262",["loot_name"] = "Syphon of the Nathrezim",["prio"] = "Enhancement Shaman > DPS Warrior > Rogue",["loot_zone"] = "Black Temple",["loot_bosses"] = "Supremus",},
    {["loot_id"] = "32255",["loot_name"] = "Felstone Bulwark",["prio"] = "Holy Paladin > Resto Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "Supremus",},
    {["loot_id"] = "32253",["loot_name"] = "Legionkiller",["prio"] = "Hunter > Prot Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Supremus",},
    {["loot_id"] = "32513",["loot_name"] = "Wristbands of Divine Influence",["prio"] = "Holy Priest > Resto Druid",["loot_zone"] = "Black Temple",["loot_bosses"] = "Shade of Akama",},
    {["loot_id"] = "32271",["loot_name"] = "Kilt of Immortal Nature",["prio"] = "Resto Druid > Resto Shaman = Holy Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Shade of Akama",},
    {["loot_id"] = "32275",["loot_name"] = "Spiritwalker Gauntlets",["prio"] = "Resto Shaman > Holy Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Shade of Akama",},
    {["loot_id"] = "32276",["loot_name"] = "Flashfire Girdle",["prio"] = "Elemental Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "Shade of Akama",},
    {["loot_id"] = "32279",["loot_name"] = "The Seeker's Wristguards",["prio"] = "Prot Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Shade of Akama",},
    {["loot_id"] = "32278",["loot_name"] = "Grips of Silent Justice",["prio"] = "Fury Warrior > Arms Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Shade of Akama",},
    {["loot_id"] = "32263",["loot_name"] = "Praetorian's Legguards",["prio"] = "Prot Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Shade of Akama",},
    {["loot_id"] = "32268",["loot_name"] = "Myrmidon's Treads",["prio"] = "Prot Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Shade of Akama",},
    {["loot_id"] = "32266",["loot_name"] = "Ring of Deceitful Intent",["prio"] = "Feral Druid (Bear) > BM Hunter > Rogue > Enhancement Shaman = Survival Hunter",["loot_zone"] = "Black Temple",["loot_bosses"] = "Shade of Akama",},
    {["loot_id"] = "32337",["loot_name"] = "Shroud of Forgiveness",["prio"] = "Non Sunshower > Resto Druid",["loot_zone"] = "Black Temple",["loot_bosses"] = "Gurtogg Bloodboil",},
    {["loot_id"] = "32339",["loot_name"] = "Belt of Primal Majesty",["prio"] = "Resto Druid > Resto Shaman > Holy Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Gurtogg Bloodboil",},
    {["loot_id"] = "32342",["loot_name"] = "Girdle of Mighty Resolve",["prio"] = "Prot Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Gurtogg Bloodboil",},
    {["loot_id"] = "32333",["loot_name"] = "Girdle of Stability",["prio"] = "Prot Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Gurtogg Bloodboil",},
    {["loot_id"] = "32341",["loot_name"] = "Leggings of Divine Retribution",["prio"] = "DPS Warrior > Ret Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Gurtogg Bloodboil",},
    {["loot_id"] = "32335",["loot_name"] = "Unstoppable Aggressor's Ring",["prio"] = "DPS Warrior > Ret Paladin = Enhancement Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "Gurtogg Bloodboil",},
    {["loot_id"] = "32501",["loot_name"] = "Shadowmoon Insignia",["prio"] = "Feral Druid (Bear) = Prot Warrior = Prot Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Gurtogg Bloodboil",},
    {["loot_id"] = "32343",["loot_name"] = "Wand of Prismatic Focus",["prio"] = "Shadow Priest > Destruction Warlock > Arcane Mage",["loot_zone"] = "Black Temple",["loot_bosses"] = "Gurtogg Bloodboil",},
    {["loot_id"] = "32351",["loot_name"] = "Elunite Empowered Bracers",["prio"] = "Balance Druid",["loot_zone"] = "Black Temple",["loot_bosses"] = "Reliquary of the Lost",},
    {["loot_id"] = "32347",["loot_name"] = "Grips of Damnation",["prio"] = "Enhancement Shaman > MS>OS",["loot_zone"] = "Black Temple",["loot_bosses"] = "Reliquary of the Lost",},
    {["loot_id"] = "32352",["loot_name"] = "Naturewarden's Treads",["prio"] = "Balance Druid = Elemental Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "Reliquary of the Lost",},
    {["loot_id"] = "32346",["loot_name"] = "Boneweave Girdle",["prio"] = "Hunter > Enhancement Shaman > Ret Paladin > DPS Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Reliquary of the Lost",},
    {["loot_id"] = "32345",["loot_name"] = "Dreadboots of the Legion",["prio"] = "DPS Warrior > Ret Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Reliquary of the Lost",},
    {["loot_id"] = "32349",["loot_name"] = "Translucent Spellthread Necklace",["prio"] = "Destruction Warlock > Shadow Priest",["loot_zone"] = "Black Temple",["loot_bosses"] = "Reliquary of the Lost",},
    {["loot_id"] = "32362",["loot_name"] = "Pendant of Titans",["prio"] = "Prot Warrior > Feral Druid (Bear)",["loot_zone"] = "Black Temple",["loot_bosses"] = "Reliquary of the Lost",},
    {["loot_id"] = "32350",["loot_name"] = "Touch of Inspiration",["prio"] = "Holy Priest = Resto Druid",["loot_zone"] = "Black Temple",["loot_bosses"] = "Reliquary of the Lost",},
    {["loot_id"] = "32332",["loot_name"] = "Torch of the Damned",["prio"] = "Ret Paladin > DPS Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Reliquary of the Lost",},
    {["loot_id"] = "32363",["loot_name"] = "Naaru-Blessed Life Rod",["prio"] = "Holy Priest",["loot_zone"] = "Black Temple",["loot_bosses"] = "Reliquary of the Lost",},
    {["loot_id"] = "32323",["loot_name"] = "Shadowmoon Destroyer's Drape",["prio"] = "DPS Warrior = Rogue = Enhancement Shaman > BM Hunter = Ret Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Teron Gorefiend",},
    {["loot_id"] = "32329",["loot_name"] = "Cowl of Benevolence",["prio"] = "Holy Priest > Resto Druid",["loot_zone"] = "Black Temple",["loot_bosses"] = "Teron Gorefiend",},
    {["loot_id"] = "32324",["loot_name"] = "Insidious Bands",["prio"] = "Survival Hunter = BM Hunter > Rogue > Enhancement Shaman > DPS Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Teron Gorefiend",},
    {["loot_id"] = "32328",["loot_name"] = "Botanist's Gloves of Growth",["prio"] = "Resto Druid > Resto Shaman > Holy Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Teron Gorefiend",},
    {["loot_id"] = "32510",["loot_name"] = "Softstep Boots of Tracking",["prio"] = "Enhancement Shaman > BM Hunter > Ret Paladin > DPS Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Teron Gorefiend",},
    {["loot_id"] = "32280",["loot_name"] = "Gauntlets of Enforcement",["prio"] = "Prot Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Teron Gorefiend",},
    {["loot_id"] = "32512",["loot_name"] = "Girdle of Lordaeron's Fallen",["prio"] = "Holy Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Teron Gorefiend",},
    {["loot_id"] = "32330",["loot_name"] = "Totem of Ancestral Guidance",["prio"] = "Elemental Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "Teron Gorefiend",},
    {["loot_id"] = "32326",["loot_name"] = "Twisted Blades of Zarak",["prio"] = "DPS Warrior > Rogue",["loot_zone"] = "Black Temple",["loot_bosses"] = "Teron Gorefiend",},
    {["loot_id"] = "32325",["loot_name"] = "Rifle of the Stoic Guardian",["prio"] = "Prot Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Teron Gorefiend",},
    {["loot_id"] = "32366",["loot_name"] = "Shadowmaster's Boots",["prio"] = "Survival Hunter > Ret Paladin > BM Hunter = Enhancement Shaman = Rogue = Feral Druid (Cat)/Warden",["loot_zone"] = "Black Temple",["loot_bosses"] = "Mother Shahraz",},
    {["loot_id"] = "32370",["loot_name"] = "Nadina's Pendant of Purity",["prio"] = "Holy Paladin > Resto Shaman > Holy Priest > Resto Druid",["loot_zone"] = "Black Temple",["loot_bosses"] = "Mother Shahraz",},
    {["loot_id"] = "32368",["loot_name"] = "Tome of the Lightbringer",["prio"] = "Prot Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Mother Shahraz",},
    {["loot_id"] = "32369",["loot_name"] = "Blade of Savagery",["prio"] = "Rogue > Prot Warrior > DPS Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Mother Shahraz",},
    {["loot_id"] = "31101",["loot_name"] = "Pauldrons of the Forgotten Conqueror",["prio"] = "Prot Paladin > Destruction Warlock > Shadow Priest > Holy Paladin > Holy Priest > Ret Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Mother Shahraz",},
    {["loot_id"] = "31103",["loot_name"] = "Pauldrons of the Forgotten Protector",["prio"] = "Fury Warrior > BM Hunter > Survival Hunter > Arms Warrior > Elemental Shaman > Resto Shaman > Prot Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Mother Shahraz",},
    {["loot_id"] = "31102",["loot_name"] = "Pauldrons of the Forgotten Vanquisher",["prio"] = "Feral Druid (Bear) > Rogue > Feral Druid (Cat) > Balance Druid > Resto Druid > Mage",["loot_zone"] = "Black Temple",["loot_bosses"] = "Mother Shahraz",},
    {["loot_id"] = "32331",["loot_name"] = "Cloak of the Illidari Council",["prio"] = "Destruction Warlock > Balance Druid = Elemental Shaman = Arcane Mage > Shadow Priest",["loot_zone"] = "Black Temple",["loot_bosses"] = "The Illidari Council",},
    {["loot_id"] = "32519",["loot_name"] = "Belt of Divine Guidance",["prio"] = "Holy Priest = Resto Druid",["loot_zone"] = "Black Temple",["loot_bosses"] = "The Illidari Council",},
    {["loot_id"] = "32376",["loot_name"] = "Forest Prowler's Helm",["prio"] = "BM Hunter = Ret Paladin > Enhancement Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "The Illidari Council",},
    {["loot_id"] = "32373",["loot_name"] = "Helm of the Illidari Shatterer",["prio"] = "Fury Warrior > Arms Warrior > Ret Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "The Illidari Council",},
    {["loot_id"] = "32505",["loot_name"] = "Madness of the Betrayer",["prio"] = "Fury Warrior > Arms Warrior > Survival Hunter > BM Hunter > Enhancement Shaman > Feral Druid (Cat)/Warden",["loot_zone"] = "Black Temple",["loot_bosses"] = "The Illidari Council",},
    {["loot_id"] = "31098",["loot_name"] = "Leggings of the Forgotten Conqueror",["prio"] = "Prot Paladin > Destruction Warlock > Holy Paladin > Shadow Priest > Holy Priest > Ret Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "The Illidari Council",},
    {["loot_id"] = "31100",["loot_name"] = "Leggings of the Forgotten Protector",["prio"] = "BM Hunter > Prot Warrior > Resto Shaman > Elemental Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "The Illidari Council",},
    {["loot_id"] = "31099",["loot_name"] = "Leggings of the Forgotten Vanquisher",["prio"] = "Feral Druid (Bear) > Rogue > Arcane Mage > Feral Druid (Cat) > Resto Druid > Balance Druid",["loot_zone"] = "Black Temple",["loot_bosses"] = "The Illidari Council",},
    {["loot_id"] = "32524",["loot_name"] = "Shroud of the Highborne",["prio"] = "(Healer Prio) > Holy Priest >= Resto Shaman > Resto Druid > Holy Paladin > (DPS Prio) > Arcane Mage = Destruction Warlock > Balance Druid = Elemental Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "32525",["loot_name"] = "Cowl of the Illidari High Lord",["prio"] = "Balance Druid > Destruction Warlock = Elemental Shaman = Mage",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "32235",["loot_name"] = "Cursed Vision of Sargeras",["prio"] = "Enhancement Shaman = BM Hunter = Ret Paladin > Fury Warrior > Kebab > Rogue > 2H Arms Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "32521",["loot_name"] = "Faceplate of the Impenetrable",["prio"] = "Prot Warrior > Prot Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "32497",["loot_name"] = "Stormrage Signet Ring",["prio"] = "Rogue > Enhancement Shaman > BM Hunter = Fury Warrior = Arms Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "32483",["loot_name"] = "The Skull of Gul'dan",["prio"] = "Destruction Warlock > Arcane Mage = Balance Druid > Elemental Shaman > Shadow Priest",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "32496",["loot_name"] = "Memento of Tyrande",["prio"] = "Resto Shaman > Holy Paladin = Holy Priest = Resto Druid",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "32500",["loot_name"] = "Crystal Spire of Karabor",["prio"] = "Holy Priest > Resto Shaman > Holy Paladin > Resto Druid",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "32374",["loot_name"] = "Zhar'doom, Greatstaff of the Devourer",["prio"] = "Balance Druid = Elemental Shaman = Shadow Priest = Destruction Warlock >= Arcane Mage",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "32375",["loot_name"] = "Bulwark of Azzinoth",["prio"] = "Prot Paladin > Prot Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "32336",["loot_name"] = "Black Bow of the Betrayer",["prio"] = "Survival Hunter > BM Hunter",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "31089",["loot_name"] = "Chestguard of the Forgotten Conqueror",["prio"] = "Prot Paladin > Shadow Priest > Holy Paladin > Holy Priest > Destruction Warlock",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "31091",["loot_name"] = "Chestguard of the Forgotten Protector",["prio"] = "Fury Warrior > BM Hunter > Survival Hunter > Arms Warrior > Elemental Shaman > Resto Shaman > Prot Warrior",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "31090",["loot_name"] = "Chestguard of the Forgotten Vanquisher",["prio"] = "Feral Druid (Bear) > Rogue > Feral Druid (Cat) > Balance Druid > Resto Druid > Mage",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "32837",["loot_name"] = "Warglaive of Azzinoth",["prio"] = "DPS Warrior = Rogue",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "32838",["loot_name"] = "Warglaive of Azzinoth",["prio"] = "DPS Warrior = Rogue",["loot_zone"] = "Black Temple",["loot_bosses"] = "Illidan Stormrage",},
    {["loot_id"] = "32590",["loot_name"] = "Nethervoid Cloak",["prio"] = "Shadow Priest > Destruction Warlock",["loot_zone"] = "Black Temple",["loot_bosses"] = "Trash",},
    {["loot_id"] = "34012",["loot_name"] = "Shroud of the Final Stand",["prio"] = "Holy Paladin = Resto Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "Trash",},
    {["loot_id"] = "32609",["loot_name"] = "Boots of the Divine Light",["prio"] = "Holy Priest > Resto Druid > Resto Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "Trash",},
    {["loot_id"] = "32593",["loot_name"] = "Treads of the Den Mother",["prio"] = "Feral Druid (Bear)",["loot_zone"] = "Black Temple",["loot_bosses"] = "Trash",},
    {["loot_id"] = "32591",["loot_name"] = "Choker of Serrated Blades",["prio"] = "BM Hunter > DPS Warrior > Enhancement Shaman > Feral Druid (Cat)/Warden = Rogue",["loot_zone"] = "Black Temple",["loot_bosses"] = "Trash",},
    {["loot_id"] = "32526",["loot_name"] = "Band of Devastation",["prio"] = "Ret Paladin > DPS Warrior = Enhancement Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "Trash",},
    {["loot_id"] = "32528",["loot_name"] = "Blessed Band of Karabor",["prio"] = "Non LW Resto > Resto Shaman = Holy Priest > Resto Druid > Holy Paladin",["loot_zone"] = "Black Temple",["loot_bosses"] = "Trash",},
    {["loot_id"] = "32527",["loot_name"] = "Ring of Ancient Knowledge",["prio"] = "Destruction Warlock (1) = Arcane Mage (1) > Shadow Priest (1) > Destruction Warlock (2) = Shadow Priest (2) = Balance Druid = Elemental Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "Trash",},
    {["loot_id"] = "34011",["loot_name"] = "Illidari Runeshield",["prio"] = "Prot Paladin > Elemental Shaman",["loot_zone"] = "Black Temple",["loot_bosses"] = "Trash",},
    {["loot_id"] = "32748",["loot_name"] = "Bindings of Lightning Reflexes",["prio"] = "Ret Paladin > Enhancement Shaman > Hunter > DPS Warrior",["loot_zone"] = "Mount Hyjal/Black Temple",["loot_bosses"] = "Patterns",},
    {["loot_id"] = "32744",["loot_name"] = "Bracers of Renewed Life",["prio"] = "Resto Druid",["loot_zone"] = "Mount Hyjal/Black Temple",["loot_bosses"] = "Patterns",},
    {["loot_id"] = "32750",["loot_name"] = "Living Earth Bindings",["prio"] = "Resto Shaman",["loot_zone"] = "Mount Hyjal/Black Temple",["loot_bosses"] = "Patterns",},
    {["loot_id"] = "32745",["loot_name"] = "Shoulderpads of Renewed Life",["prio"] = "Resto Druid",["loot_zone"] = "Mount Hyjal/Black Temple",["loot_bosses"] = "Patterns",},
    {["loot_id"] = "32747",["loot_name"] = "Swiftstrike Shoulders",["prio"] = "Enhancement Shaman > Ret Paladin > Hunter > DPS Warrior",["loot_zone"] = "Mount Hyjal/Black Temple",["loot_bosses"] = "Patterns",},
    {["loot_id"] = "32754",["loot_name"] = "Bracers of Nimble Thought",["prio"] = "Shadow Priest > Destruction Warlock = Elemental Shaman = Balance Druid > Arcane Mage",["loot_zone"] = "Mount Hyjal/Black Temple",["loot_bosses"] = "Patterns",},
    {["loot_id"] = "32755",["loot_name"] = "Mantle of Nimble Thought",["prio"] = "Shadow Priest > Destruction Warlock > MS>OS",["loot_zone"] = "Black Temple",["loot_bosses"] = "Patterns",},
    {["loot_id"] = "32753",["loot_name"] = "Swiftheal Mantle",["prio"] = "Resto Druid > Holy Priest",["loot_zone"] = "Mount Hyjal/Black Temple",["loot_bosses"] = "Patterns",},
    {["loot_id"] = "32752",["loot_name"] = "Swiftheal Wraps",["prio"] = "Resto Druid > Holy Priest",["loot_zone"] = "Mount Hyjal/Black Temple",["loot_bosses"] = "Patterns",},
}
